In [1]:
!pip install gym==0.25.2

In [2]:
import numpy as np
import gym
import random

In [3]:
env = gym.make("FrozenLake-v1")

c:\Users\RAB\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
c:\Users\RAB\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\wrappers\step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [4]:
action_size = env.action_space.n
state_size = env.observation_space.n

print(action_size)
print(state_size)

4
16


In [5]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
total_episodes = 100000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential

In [7]:
# List of rewards
rewards = []
ic=0
# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
    ic=ic+1
    if ic>1000:
        ic=0
        print(episode, total_rewards)
    episode += 1
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

1000 0.0
2001 1.0
3002 0.0
4003 0.0
5004 0.0
6005 0.0
7006 0.0
8007 1.0
9008 0.0
10009 1.0
11010 1.0
12011 1.0
13012 1.0
14013 1.0
15014 1.0
16015 1.0
17016 0.0
18017 1.0
19018 1.0
20019 0.0
21020 0.0
22021 1.0
23022 0.0
24023 1.0
25024 1.0
26025 1.0
27026 1.0
28027 0.0
29028 0.0
30029 1.0
31030 0.0
32031 1.0
33032 1.0
34033 1.0
35034 0.0
36035 1.0
37036 0.0
38037 0.0
39038 1.0
40039 1.0
41040 0.0
42041 1.0
43042 0.0
44043 1.0
45044 0.0
46045 1.0
47046 1.0
48047 1.0
49048 0.0
50049 1.0
51050 0.0
52051 1.0
53052 0.0
54053 1.0
55054 0.0
56055 0.0
57056 0.0
58057 1.0
59058 1.0
60059 1.0
61060 1.0
62061 1.0
63062 1.0
64063 1.0
65064 0.0
66065 0.0
67066 0.0
68067 1.0
69068 1.0
70069 0.0
71070 1.0
72071 0.0
73072 1.0
74073 0.0
75074 1.0
76075 1.0
77076 0.0
78077 1.0
79078 1.0
80079 0.0
81080 0.0
82081 0.0
83082 0.0
84083 1.0
85084 0.0
86085 0.0
87086 1.0
88087 0.0
89088 1.0
90089 1.0
91090 0.0
92091 0.0
93092 1.0
94093 1.0
95094 1.0
96095 0.0
97096 0.0
98097 1.0
99098 0.0
Score over time: 0.

In [8]:
print(qtable)

[[5.84578922e-02 2.79837400e-02 4.05224003e-02 9.05557410e-03]
 [3.46954517e-03 3.63528429e-03 5.58968756e-04 4.56455058e-03]
 [1.88855041e-03 1.74192919e-03 3.01528147e-03 9.46467931e-03]
 [7.61103064e-04 1.04328475e-04 1.93355327e-03 2.22303845e-02]
 [2.90069791e-01 8.12041573e-03 4.34754066e-04 1.70203021e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.03557067e-05 1.88470220e-03 3.17400965e-05 2.39991651e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.19177364e-03 1.74808330e-02 1.83361746e-03 3.71267212e-01]
 [2.44676229e-03 4.00039392e-01 6.18914807e-04 4.50117483e-03]
 [6.30889312e-01 3.91552653e-04 9.49705994e-05 9.42950258e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.49479369e-04 5.56098310e-03 7.24891943e-01 5.05912069e-02]
 [2.14553031e-01 9.50833625e-01 7.21548148e-02 1.48194226e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [9]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            break
        state = new_state
# env.close()

****************************************************
EPISODE  0


c:\Users\RAB\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(
c:\Users\RAB\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:49: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See

****************************************************
EPISODE  1
****************************************************
EPISODE  2
****************************************************
EPISODE  3
****************************************************
EPISODE  4


In [10]:
env.close()